/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/teams/': RouteRecordInfo<'/teams/', '/teams', Record<never, never>, Record<never, never>>,
    '/teams/[teamId]/': RouteRecordInfo<'/teams/[teamId]/', '/teams/:teamId', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/': RouteRecordInfo<'/teams/[teamId]/competitions/', '/teams/:teamId/competitions', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/[competitionId]/': RouteRecordInfo<'/teams/[teamId]/competitions/[competitionId]/', '/teams/:teamId/competitions/:competitionId', { teamId: ParamValue<true>, competitionId: ParamValue<true> }, { teamId: ParamValue<false>, competitionId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/[competitionId]/edit': RouteRecordInfo<'/teams/[teamId]/competitions/[competitionId]/edit', '/teams/:teamId/competitions/:competitionId/edit', { teamId: ParamValue<true>, competitionId: ParamValue<true> }, { teamId: ParamValue<false>, competitionId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/new': RouteRecordInfo<'/teams/[teamId]/competitions/new', '/teams/:teamId/competitions/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/edit': RouteRecordInfo<'/teams/[teamId]/edit', '/teams/:teamId/edit', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/matches/': RouteRecordInfo<'/teams/[teamId]/matches/', '/teams/:teamId/matches', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/matches/[matchId]/': RouteRecordInfo<'/teams/[teamId]/matches/[matchId]/', '/teams/:teamId/matches/:matchId', { teamId: ParamValue<true>, matchId: ParamValue<true> }, { teamId: ParamValue<false>, matchId: ParamValue<false> }>,
    '/teams/[teamId]/matches/[matchId]/edit': RouteRecordInfo<'/teams/[teamId]/matches/[matchId]/edit', '/teams/:teamId/matches/:matchId/edit', { teamId: ParamValue<true>, matchId: ParamValue<true> }, { teamId: ParamValue<false>, matchId: ParamValue<false> }>,
    '/teams/[teamId]/matches/new': RouteRecordInfo<'/teams/[teamId]/matches/new', '/teams/:teamId/matches/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/': RouteRecordInfo<'/teams/[teamId]/players/', '/teams/:teamId/players', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/[playerId]/': RouteRecordInfo<'/teams/[teamId]/players/[playerId]/', '/teams/:teamId/players/:playerId', { teamId: ParamValue<true>, playerId: ParamValue<true> }, { teamId: ParamValue<false>, playerId: ParamValue<false> }>,
    '/teams/[teamId]/players/[playerId]/edit': RouteRecordInfo<'/teams/[teamId]/players/[playerId]/edit', '/teams/:teamId/players/:playerId/edit', { teamId: ParamValue<true>, playerId: ParamValue<true> }, { teamId: ParamValue<false>, playerId: ParamValue<false> }>,
    '/teams/[teamId]/players/development': RouteRecordInfo<'/teams/[teamId]/players/development', '/teams/:teamId/players/development', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/import': RouteRecordInfo<'/teams/[teamId]/players/import', '/teams/:teamId/players/import', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/new': RouteRecordInfo<'/teams/[teamId]/players/new', '/teams/:teamId/players/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/squads': RouteRecordInfo<'/teams/[teamId]/players/squads', '/teams/:teamId/players/squads', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/statistics': RouteRecordInfo<'/teams/[teamId]/players/statistics', '/teams/:teamId/players/statistics', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/seasons/[season]': RouteRecordInfo<'/teams/[teamId]/seasons/[season]', '/teams/:teamId/seasons/:season', { teamId: ParamValue<true>, season: ParamValue<true> }, { teamId: ParamValue<false>, season: ParamValue<false> }>,
    '/teams/new': RouteRecordInfo<'/teams/new', '/teams/new', Record<never, never>, Record<never, never>>,
  }
}
