/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/auth/[credentials]': RouteRecordInfo<'/auth/[credentials]', '/auth/:credentials', { credentials: ParamValue<true> }, { credentials: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/teams/': RouteRecordInfo<'/teams/', '/teams', Record<never, never>, Record<never, never>>,
    '/teams/[teamId]/': RouteRecordInfo<'/teams/[teamId]/', '/teams/:teamId', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/': RouteRecordInfo<'/teams/[teamId]/competitions/', '/teams/:teamId/competitions', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/[competitionId]/': RouteRecordInfo<'/teams/[teamId]/competitions/[competitionId]/', '/teams/:teamId/competitions/:competitionId', { teamId: ParamValue<true>, competitionId: ParamValue<true> }, { teamId: ParamValue<false>, competitionId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/[competitionId]/edit': RouteRecordInfo<'/teams/[teamId]/competitions/[competitionId]/edit', '/teams/:teamId/competitions/:competitionId/edit', { teamId: ParamValue<true>, competitionId: ParamValue<true> }, { teamId: ParamValue<false>, competitionId: ParamValue<false> }>,
    '/teams/[teamId]/competitions/new': RouteRecordInfo<'/teams/[teamId]/competitions/new', '/teams/:teamId/competitions/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/edit': RouteRecordInfo<'/teams/[teamId]/edit', '/teams/:teamId/edit', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/matches/': RouteRecordInfo<'/teams/[teamId]/matches/', '/teams/:teamId/matches', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/matches/[matchId]/': RouteRecordInfo<'/teams/[teamId]/matches/[matchId]/', '/teams/:teamId/matches/:matchId', { teamId: ParamValue<true>, matchId: ParamValue<true> }, { teamId: ParamValue<false>, matchId: ParamValue<false> }>,
    '/teams/[teamId]/matches/[matchId]/edit': RouteRecordInfo<'/teams/[teamId]/matches/[matchId]/edit', '/teams/:teamId/matches/:matchId/edit', { teamId: ParamValue<true>, matchId: ParamValue<true> }, { teamId: ParamValue<false>, matchId: ParamValue<false> }>,
    '/teams/[teamId]/matches/new': RouteRecordInfo<'/teams/[teamId]/matches/new', '/teams/:teamId/matches/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/': RouteRecordInfo<'/teams/[teamId]/players/', '/teams/:teamId/players', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/[playerId]/': RouteRecordInfo<'/teams/[teamId]/players/[playerId]/', '/teams/:teamId/players/:playerId', { teamId: ParamValue<true>, playerId: ParamValue<true> }, { teamId: ParamValue<false>, playerId: ParamValue<false> }>,
    '/teams/[teamId]/players/[playerId]/edit': RouteRecordInfo<'/teams/[teamId]/players/[playerId]/edit', '/teams/:teamId/players/:playerId/edit', { teamId: ParamValue<true>, playerId: ParamValue<true> }, { teamId: ParamValue<false>, playerId: ParamValue<false> }>,
    '/teams/[teamId]/players/development': RouteRecordInfo<'/teams/[teamId]/players/development', '/teams/:teamId/players/development', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/import': RouteRecordInfo<'/teams/[teamId]/players/import', '/teams/:teamId/players/import', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/new': RouteRecordInfo<'/teams/[teamId]/players/new', '/teams/:teamId/players/new', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/players/statistics': RouteRecordInfo<'/teams/[teamId]/players/statistics', '/teams/:teamId/players/statistics', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/[teamId]/seasons/[season]': RouteRecordInfo<'/teams/[teamId]/seasons/[season]', '/teams/:teamId/seasons/:season', { teamId: ParamValue<true>, season: ParamValue<true> }, { teamId: ParamValue<false>, season: ParamValue<false> }>,
    '/teams/[teamId]/squads/': RouteRecordInfo<'/teams/[teamId]/squads/', '/teams/:teamId/squads', { teamId: ParamValue<true> }, { teamId: ParamValue<false> }>,
    '/teams/new': RouteRecordInfo<'/teams/new', '/teams/new', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
