name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: '18'
      - name: Install
        run: yarn install
      - name: ESLint
        run: yarn lint
      - name: Prettier
        run: yarn format
      - name: Vue TSC
        run: yarn lint:tsc
