name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node_version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Install
        run: pnpm install
      - name: ESLint
        run: pnpm run lint
      - name: Prettier
        run: pnpm run format:check
      - name: Vue TSC
        run: pnpm run lint:tsc
